<a href="https://colab.research.google.com/github/ThanhTad/Lab_ML/blob/main/Lab_4_20130222_CaoThanhDat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This lab is to continous dealing with **Logistic Regression**, **kNN**, and **Decision Tree** alogirthms applied to classification tasks. 

*   **Deadline: 23:59, 12/03/2023**



# Import libraries

In [12]:
# code
import numpy as np
from sklearn.linear_model import LogisticRegression 
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.neighbors import KNeighborsClassifier
from google.colab import drive
drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/lab4_ml'
import pandas as pd 
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
/content/gdrive/MyDrive/lab4_ml


#Task 1. 
Apply **LogisticRegression** to iris dataset which aims at classifying species of iris based on sepal_length (chiều dài đài hoa), sepal_width, petal_length (chiều dài cánh hoa), petal_width. The species are '**setosa**' '**versicolor**' and '**virginica**'. 



```
from sklearn import datasets
data4 = datasets.load_iris()
```




In [ ]:
# code  
data4 = datasets.load_iris()
X_train, X_test, Y_train, Y_test = train_test_split(data4.data, data4.target, test_size = 0.25)
classifier = LogisticRegression(random_state = 0) 
classifier.fit(X_train, Y_train)

y_pred = classifier.predict(X_test)

print("confusion matrix: \n", confusion_matrix(Y_test, y_pred))
print("precision: ", precision_score(Y_test, y_pred, average='micro'))
print("recall: ", recall_score(Y_test, y_pred, average='micro'))
print("f1: ", f1_score(Y_test, y_pred, average='micro'))




confusion matrix: 
 [[ 9  0  0]
 [ 0 16  1]
 [ 0  0 12]]
precision:  0.9736842105263158
recall:  0.9736842105263158
f1:  0.9736842105263158


#Task 2. 
Apply LogisticRegression to **MNIST** dataset (mnist.csv) which aims at classifying handwritten digits. Dataset includes 784 pixels values of images (28x28). 


```
from sklearn import datasets
# load the MNIST digits dataset
mnist = datasets.load_digits()
```



In [ ]:
# code
mnist = datasets.load_digits()
X_train, X_test, Y_train, Y_test = train_test_split(mnist.data, mnist.target, test_size = 0.25)
classifier = LogisticRegression(random_state = 0) 
classifier.fit(X_train, Y_train)

y_pred = classifier.predict(X_test)

print("confusion matrix: \n", confusion_matrix(Y_test, y_pred))
print("precision: ", precision_score(Y_test, y_pred, average='micro'))
print("recall: ", recall_score(Y_test, y_pred, average='micro'))
print("f1: ", f1_score(Y_test, y_pred, average='micro'))


confusion matrix: 
 [[51  0  0  0  0  0  0  0  0  0]
 [ 0 41  0  1  0  0  0  0  1  0]
 [ 0  0 31  0  0  0  0  0  0  0]
 [ 0  0  0 49  0  0  0  0  0  1]
 [ 0  0  0  0 36  0  0  1  0  2]
 [ 0  0  0  0  0 39  2  1  1  0]
 [ 0  0  0  0  0  0 42  0  0  0]
 [ 0  0  0  0  1  0  0 47  0  0]
 [ 0  5  0  0  0  0  0  0 41  0]
 [ 0  0  0  0  0  0  0  1  1 55]]
precision:  0.96
recall:  0.96
f1:  0.96


/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


#Task 3. 
Apply another classification algorithm named kNN, which is an instance classifcation model. 
*  3.1. Perform kNN algorithm to Iris dataset with k={1, 3, 5, …, 29}. Select the best value of k.

*   3.2. Then compare the obtained results with those using Logistic regression (based on metrics: accuracy, precision, recall, f1 measure).


In [ ]:
# code
k_range = np.arange(1, 30, 2)
data4 = datasets.load_iris()
X_train, X_test, Y_train, Y_test = train_test_split(data4.data, data4.target, test_size = 0.25)
acls = []
precision=[]
recall = []
f1 = []

for k in k_range:
  model = KNeighborsClassifier(n_neighbors=k)
  model.fit(X_train, Y_train)
  y_pred = model.predict(X_test)
  acls.append(y_pred)
  precision.append(precision_score(Y_test, y_pred, average='micro'))
  recall.append(recall_score(Y_test, y_pred, average='micro'))
  f1.append(f1_score(Y_test, y_pred, average='micro'))

print(f1)





[0.9736842105263158, 0.9736842105263158, 0.9736842105263158, 0.9736842105263158, 0.9736842105263158, 0.9736842105263158, 0.9736842105263158, 0.9736842105263158, 0.9736842105263158, 0.9736842105263158, 0.9736842105263158, 0.9736842105263158, 0.9736842105263158, 0.9736842105263158, 0.9473684210526315]


#Task 4. 
Similar to Task 3, apply kNN algorithm to **mnist** dataset which included in datasets of sklearn API.
*  4.1.	Perform kNN algorithm to Iris dataset with k={1, 3, 5, …, 29}. Select the best value of k.
*  4.2.	Then compare the obtained results with those using Logistic regression (based on metrics: accuracy, precision, recall, f1 measure).


In [ ]:
# code
k_range = np.arange(1, 30, 2)
mnist = datasets.load_digits()
X_train, X_test, Y_train, Y_test = train_test_split(mnist.data, mnist.target, test_size = 0.25)
acls = []
precision=[]
recall = []
f1 = []

for k in k_range:
  model = KNeighborsClassifier(n_neighbors=k)
  model.fit(X_train, Y_train)
  y_pred = model.predict(X_test)
  acls.append(y_pred)
  precision.append(precision_score(Y_test, y_pred, average='micro'))
  recall.append(recall_score(Y_test, y_pred, average='micro'))
  f1.append(f1_score(Y_test, y_pred, average='micro'))

print(f1)

[0.9911111111111112, 0.9866666666666668, 0.9888888888888889, 0.9822222222222222, 0.9844444444444445, 0.9822222222222222, 0.9733333333333334, 0.9711111111111111, 0.9666666666666667, 0.9666666666666667, 0.9622222222222222, 0.9622222222222222, 0.9622222222222222, 0.9622222222222222, 0.96]


#Task 5. 
Compare the performance of selected classification algorithms (**Decision Treen, kNN, and Logistic Regression**) to ***spam detection***. The dataset can be accessed from the link: http://archive.ics.uci.edu/ml/datasets/Spambase 
Attribute Information:
The last column of 'spambase.csv denotes whether the e-mail was considered spam (1) or not (0), i.e. unsolicited commercial e-mail. Most of the attributes indicate whether a particular word or character was frequently occuring in the e-mail. The run-length attributes (55-57) measure the length of sequences of consecutive capital letters. For the statistical measures of each attribute, see the end of this file. Here are the definitions of the attributes: 
*  48 continuous real [0,100] attributes of type word_freq_WORD 
= percentage of words in the e-mail that match WORD, i.e. 100 * (number of times the WORD appears in the e-mail) / total number of words in e-mail. A "word" in this case is any string of alphanumeric characters bounded by non-alphanumeric characters or end-of-string. **Example**: word_freq_address: percentage of words in the e-mail that match ADDRESS.
*  6 continuous real [0,100] attributes of type char_freq_CHAR] 
= percentage of characters in the e-mail that match CHAR, i.e. 100 * (number of CHAR occurences) / total characters in e-mail
*  1 continuous real [1,...] attribute of type capital_run_length_average 
= average length of uninterrupted sequences of capital letters
*  1 continuous integer [1,...] attribute of type capital_run_length_longest 
= length of longest uninterrupted sequence of capital letters
*  1 continuous integer [1,...] attribute of type capital_run_length_total = sum of length of uninterrupted sequences of capital letters = total number of capital letters in the e-mail
*  1 nominal {0,1} class attribute of type spam = denotes whether the e-mail was considered spam (1) or not (0), i.e. unsolicited commercial e-mail. 


---


In order to compare the performance of selected algorithms, some common metrics including **accuracy, precision, recall, f1 measures** could be used.


In [19]:
# code
df = pd.read_csv("spambase.csv")
X_train, X_test, Y_train, Y_test = train_test_split(mnist.data, mnist.target, test_size = 0.25)
#Logistic Regression
classifier = LogisticRegression(random_state = 0) 
classifier.fit(X_train, Y_train)
y_pred = classifier.predict(X_test)
print("Logistic Regression")
print("accuracy: ", accuracy_score(Y_test, y_pred))
print("precision: ", precision_score(Y_test, y_pred, average='micro'))
print("recall: ", recall_score(Y_test, y_pred, average='micro'))
print("f1: ", f1_score(Y_test, y_pred, average='micro'))

#kNN
model = KNeighborsClassifier(n_neighbors=k)
model.fit(X_train, Y_train)
y_pred2 = model.predict(X_test)
print("\nkNN")
print("accuracy: ", accuracy_score(Y_test, y_pred2))
print("precision: ", precision_score(Y_test, y_pred2, average='micro'))
print("recall: ", recall_score(Y_test, y_pred2, average='micro'))
print("f1: ", f1_score(Y_test, y_pred2, average='micro'))

#Decision Treen
clf_model = DecisionTreeClassifier(criterion="gini", random_state=42,
max_depth=3, min_samples_leaf=5)
clf_model.fit(X_train, Y_train)
# tree.plot_tree(clf)
y_predict = clf_model.predict(X_test)
print("\nDecision Treen")
print("accuracy: ", accuracy_score(Y_test, y_predict))
print("precision: ", precision_score(Y_test, y_predict, average='micro'))
print("recall: ", recall_score(Y_test, y_predict, average='micro'))
print("f1: ", f1_score(Y_test, y_predict, average='micro'))

Logistic Regression
accuracy:  0.9644444444444444
precision:  0.9644444444444444
recall:  0.9644444444444444
f1:  0.9644444444444444

kNN
accuracy:  0.9555555555555556
precision:  0.9555555555555556
recall:  0.9555555555555556
f1:  0.9555555555555556

Decision Treen
accuracy:  0.45555555555555555
precision:  0.45555555555555555
recall:  0.45555555555555555
f1:  0.45555555555555555


/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


#Finally,
Save a copy in your Github. Remember renaming the notebook.